# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        intellijVersion: [ 2020.3, 2021.1, 2021.2 ]
    runs-on: ubuntu-latest
    name: 'Publish with INTELLIJ ${{ matrix.intellijVersion }}'
    env:
      INTELLIJ_VERSION: ${{ matrix.intellijVersion }}
      INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Evaluate base version
        run: echo "BASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test base version
        run: |
          echo $BASE_VERSION
          echo ${{ env.BASE_VERSION }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build with gradle
        run: ./gradlew --warning-mode=all build
      - name: Publish plugin
        run: ./gradlew publishPlugin
